### ISSUE TITLE
addImplicitHydrogens sometimes crashes

### ISSUE THREAD

**Issue by targos** [cheminfo/openchemlib-js#114]
```js
const molfile= `
Actelion Java MolfileCreator 1.0

  9  8  0  0  0  0  0  0  0  0999 V2000
   16.6500   -9.0439   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.6500  -10.5439   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.9490  -11.2939   -0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   19.2481  -10.5439   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   19.2481   -9.0439   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.9490   -8.2939   -0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   17.9490  -12.7939   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.6500  -13.5439   -0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   20.1500  -19.1689   -0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
  3  4  1  0  0  0  0
  4  5  1  0  0  0  0
  5  6  1  0  0  0  0
  6  1  1  0  0  0  0
  3  7  1  0  0  0  0
  7  8  1  0  0  0  0
M  END
`;

require('openchemlib/dist/openchemlib-full.pretty.js').Molecule.fromMolfile(molfile).addImplicitHydrogens();

```

```
Uncaught TypeError: Cannot read property 'x_0' of undefined
    at StereoMolecule_0.getAtomX_0 [as getAtomX_1] (C:\git\cheminfo\nmrium\node_modules\openchemlib\dist\openchemlib-full.pretty.js:17740:34)
    at Object.addImplicitHydrogens_0 (C:\git\cheminfo\nmrium\node_modules\openchemlib\dist\openchemlib-full.pretty.js:31062:30)
    at Object.addImplicitHydrogens (C:\git\cheminfo\nmrium\node_modules\openchemlib\dist\openchemlib-full.pretty.js:30908:12)
    at JSMolecule_1.addImplicitHydrogens_1 [as addImplicitHydrogens_0] (C:\git\cheminfo\nmrium\node_modules\openchemlib\dist\openchemlib-full.pretty.js:48842:10)
    at JSMolecule_1.addImplicitHydrogens_3 [as addImplicitHydrogens] (C:\git\cheminfo\nmrium\node_modules\openchemlib\dist\openchemlib-full.pretty.js:48851:10)
```

**Comment by lpatiny** [comment]
Closed by 9e9c3539a479cc761dcdc69c19f63665ba810f99

**Comment by lpatiny** [comment]
@targos We should make a PR in openchemlib project but I don't know how to eslint correctly the code. I will ask Thomas.

**Comment by targos** [comment]
how to eslint?

**Comment by lpatiny** [comment]
I was thinking 'lint'.  Problem of the position of spaces, curly brackets, etc.

Related ticket : https://github.com/Actelion/openchemlib/issues/65
